### PR TITLE
week1作業繳交

### PR DESCRIPTION
**Pull request by wanhsuan625**
老師好，我是詹宛璇(Bonnie宛璇)

http://54.199.123.84:3000/api/attractions?page=0
http://54.199.123.84:3000/api/attractions?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80
http://54.199.123.84:3000/api/attractions?page=1&keyword=%E5%8C%97
http://54.199.123.84:3000/api/attraction/10
http://54.199.123.84:3000/api/categories

再麻煩老師了，謝謝~

### CODE REVIEW

**Review by cwpeng — COMMENTED** [review]
Your live URLs are broken.

**Comment by wanhsuan625** [comment]
修正完成，再麻煩老師了，不好意思🙇

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Response format of http://54.199.123.84:3000/api/attraction/10 is incorrect.
2. "images" field of attraction should be a string array containing every image URLs. For example: ["Image URL 1", "Image URL 2", ...]. But yours is actually a single string "['Image URL 1', 'Image URL 2', ...]"

Solve issues and re-request review.

**Comment by wanhsuan625** [comment]
已完成修正，再麻煩老師了，謝謝您。

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by wanhsuan625** [comment]
好~~~謝謝老師😄！

**Pull request merged**
