### PR TITLE
week3作業繳交

### PR DESCRIPTION
**Pull request by wanhsuan625**
Dear teacher,

Please review my week3 assignment,
thank you a lot！！！

My name is  **詹宛璇 ( Bonnie宛璇)**
http://54.199.123.84:3000/
http://54.199.123.84:3000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done, but there is no margin space between image slider and navigator bar in mobile version.

**Comment by wanhsuan625** [comment]
Dear teacher,

I revised the incorrect set of attraction websites.
Please check it, thank you a lot！！

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Comment by wanhsuan625** [comment]
thank you, teacher~~🙏

**Pull request merged**
